name = "allbooks.txt"
with open(name, 'w') as allbooks:
    allbooks.write("All books in the record\n\n")
    allbooks.write("Book 1\nName of the book : To Kill a Mockingbird\nAuthor of the book : Harper Lee\nThe ISSN of the book : 0378-5955\nCost of the book : $24.99\n\n")
    allbooks.write("Book 2\nName of the book : The Great Gatsby\nAuthor of the book : F.Scott Fitzgerald\nThe ISSN of the book : 1234-5679\nCost of the book : $44\n\n")
    allbooks.write("Book 3\nName of the book : Ulysses\nAuthor of the book : JamesJoyce\nThe ISSN of the book : 4324-5543\nCost of the book : $5.99\n\n")
    allbooks.write("Book 4\nName of the book : The Catcher in the Rye\nAuthor of the book : J.D Salinger\nThe ISSN of the book : 3432-3453\nCost of the book : $15.99\n\n")
    allbooks.write("Book 5\nName of the book : Pride and Prejudice\nAuthor of the book : Jane Austen\nThe ISSN of the book : 4353-2433\nCost of the book : $13.50\n\n")
    allbooks.write("Book 6\nName of the book :  In Search of Lost Time \nAuthor of the book : Marcel Proust\nThe ISSN of the book : 4235-5679\nCost of the book : $35.70\n\n")
    allbooks.write("Book 7\nName of the book : Don Quixote \nAuthor of the book : Miguel de Cervantes\nThe ISSN of the book : 7856-2343\nCost of the book : $46.77\n\n")
    allbooks.write("Book 8\nName of the book : One Hundred Years of Solitude\nAuthor of the book : Gabriel Garcia Marquez\nThe ISSN of the book : 3222-7087\nCost of the book : $75.23\n\n")
    allbooks.write("Book 9\nName of the book : Moby Dick by  \nAuthor of the book : Herman Melville\nThe ISSN of the book : 8565-4425\nCost of the book : $87.77\n\n")
    allbooks.write("Book 10\nName of the book : War and Peace  \nAuthor of the book : Leo Tolstoy\nThe ISSN of the book : 9876-2355\nCost of the book : $98.23\n\n")
    allbooks.write("Book 11\nName of the book : Hamlet  \nAuthor of the book : William Shakespeare\nThe ISSN of the book : 6544-7866\nCost of the book : $75.34\n\n")
    allbooks.write("Book 12\nName of the book : Madame Bovary \nAuthor of the book : Gustave Flaubert\nThe ISSN of the book : 5465-7675\nCost of the book : $67.46\n\n")
    allbooks.write("Book 13\nName of the book :  The Divine Comedy  \nAuthor of the book : Dante Alighieri\nThe ISSN of the book : 6543-5645\nCost of the book : $54.54\n\n")
    allbooks.write("Book 13\n")
    allbooks.write("Name of the book :  The Divine Comedy\n")
    allbooks.write("Author of the book : Dante Alighieri\n")
    allbooks.write("The ISSN of the book : 6543-5645\n")
    allbooks.write("Cost of the book : $54.54\n\n")
    allbooks.write("Book 14\n")
    allbooks.write("Name of the book : Lolita\n")
    allbooks.write("Author of the book : Vladimir Nabokov\n")
    allbooks.write("The ISSN of the book : 4532-5455\n")
    allbooks.write("Cost of the book : $98.23\n\n")
    allbooks.write("Book 15\n")
    allbooks.write("Name of the book : The Brothers Karamazov\n")
    allbooks.write("Author of the book : Fyodor Dostoyevsky\n")
    allbooks.write("The ISSN of the book : 5643-7676\n")
    allbooks.write("Cost of the book : $35.54\n\n")

    allbooks.write("Book 16\n")
    allbooks.write("Name of the book : Crime and Punishment\n")
    allbooks.write("Author of the book : Fyodor Dostoyevsky\n")
    allbooks.write("The ISSN of the book : 5643-5445\n")
    allbooks.write("Cost of the book : $65.23\n\n")

    allbooks.write("Book 17\n")
    allbooks.write("Name of the book : Wuthering Heights by\n")
    allbooks.write("Author of the book : Emily Brontë\n")
    allbooks.write("The ISSN of the book : 6534-5645\n")
    allbooks.write("Cost of the book : $34.23\n\n")

    allbooks.write("Book 18\n")
    allbooks.write("Name of the book : The Adventures of Huckleberry Finn\n")
    allbooks.write("Author of the book : Mark Twain\n")
    allbooks.write("The ISSN of the book : 4234-4352\n")
    allbooks.write("Cost of the book : $78.56\n\n")

    allbooks.write("Book 19\n")
    allbooks.write("Name of the book : Anna Karenina\n")
    allbooks.write("Author of the book : Leo Tolstoy\n")
    allbooks.write("The ISSN of the book : 7656-7886\n")
    allbooks.write("Cost of the book : $76.45\n\n")

    allbooks.write("Book 20\n")
    allbooks.write("Name of the book : Alice's Adventures in Wonderland\n")
    allbooks.write("Author of the book : Lewis Carroll\n")
    allbooks.write("The ISSN of the book : 7656-2342\n")
    allbooks.write("Cost of the book : $234.23\n\n")

    allbooks.write("Book 21\n")
    allbooks.write("Name of the book : The Iliad\n")
    allbooks.write("Author of the book : Homer\n")
    allbooks.write("The ISSN of the book : 7645-7887\n")
    allbooks.write("Cost of the book : $676.21\n\n")

    allbooks.write("Book 22\n")
    allbooks.write("Name of the book : To the Lighthouse\n")
    allbooks.write("Author of the book : Virginia Woolf\n")
    allbooks.write("The ISSN of the book : 5432-7657\n")
    allbooks.write("Cost of the book : $342.21\n\n")
    allbooks.close()
